name: TelegramConnectorPremium
version: '${project.version}'
main: wozniaktv.telegramconnector.Main
api-version: 1.19
authors: [ WoZniaK_TV ]
description: Connects your Server with a Telegram Bot
commands:
  tgpreload:
    usage: /tgpreload
    description: Reload
